@base_url=http://localhost:8081
# @name auth
GET {{base_url}}/tokenz

###
@token = {{auth.response.body.$.token}}

###
DELETE {{base_url}}/todos/18
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "test 1"
}